apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-a-podmonitor
  namespace: app-a
  labels:
    app: aplicacao-a
    version: v1
    app.kubernetes.io/component: aplicacao-a
    app.kubernetes.io/instance: aplicacao-a
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /stats/prometheus
      relabelings:
        - action: keep
          regex: istio-proxy
          sourceLabels: [__meta_kubernetes_pod_container_name]
        - action: replace
          regex: (.+);.*|.*;(.+)
          replacement: '${1}${2}'
          separator: ;
          sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app]
          targetLabel: app
        - action: replace
          regex: (.+);.*|.*;(.+)
          replacement: '${1}${2}'
          separator: ;
          sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_version, __meta_kubernetes_pod_label_version]
          targetLabel: version
  selector:
    matchExpressions:
      - key: app
        operator: Exists