# Service ClusterIP na porta 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aplicacao-a
  namespace: app-a
  labels:
    app: aplicacao-a
    version: v1
    app.kubernetes.io/component: aplicacao-a
    app.kubernetes.io/instance: aplicacao-a
spec:
  type: ClusterIP
  selector:
    deployment: aplicacao-a
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
