# Application dev — workload aplicacao-b em secure-app-b
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-aplicacao-b
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: dev
  source:
    repoURL: https://github.com/thegusmao/rhcl-rhossm.git
    targetRevision: main
    path: manifests/apps/secure-aplication-b
  destination:
    server: https://kubernetes.default.svc
    namespace: secure-app-b
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: aplicacao-b
      namespace: secure-app-b
      jsonPointers:
        - /spec/template/spec/containers/0/image
