# AuthPolicy permissiva no Gateway — acesso anônimo ao host app-a-super
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: app-a-super-permissive
  namespace: ingress-gateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: edge-gateway
  when:
    - selector: request.host
      operator: eq
      value: app-a-super.apps.cluster-vv944.dynamic2.redhatworkshops.io
  rules:
    authentication:
      anonymous:
        anonymous: {}
    authorization:
      allow-all:
        opa:
          rego: "allow = true"
