# Permite HTTPRoutes do namespace app-a anexarem ao Gateway em openshift-ingress
#---
#apiVersion: gateway.networking.k8s.io/v1beta1
#kind: ReferenceGrant
#metadata:
#  name: allow-httproutes-from-app-a
#  namespace: ingress-gateway
#spec:
#  from:
#    - group: gateway.networking.k8s.io
#      kind: HTTPRoute
#      namespace: app-a
#  to:
#    - group: gateway.networking.k8s.io
#      kind: Gateway