# Istio CNI — requerido para sidecar injection no OCP
---
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
  namespace: istio-cni
spec:
  namespace: istio-cni
  version: v1.27-latest
