# mTLS STRICT — apenas tráfego criptografado entre sidecars em secure-app-a
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: secure-app-a
spec:
  mtls:
    mode: STRICT
