# Namespace da aplicação A (projeto dev)
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-a
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    istio-discovery: enabled
    istio-injection: enabled
    openshift.io/user-monitoring: "true"
