# Namespace da aplicação A (projeto dev)
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-b
  labels:
    managed-by: openshift-gitops
    argocd.argoproj.io/managed-by: openshift-gitops
    istio-discovery: enabled
    istio-injection: "true"
