# Namespace do control plane Istio (OSSM 3 sidecar mode)
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops