# Namespace do CR Kuadrant e componentes RHCL
---
apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
