# Namespace secure-app-b — workloads com mTLS STRICT (mesh Firesoft internal CA)
---
apiVersion: v1
kind: Namespace
metadata:
  name: secure-app-b
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    istio-discovery: enabled
    istio-injection: enabled
    openshift.io/user-monitoring: "true"
